# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dsandbox"
BBFILE_PATTERN_meta-dsandbox = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dsandbox = "6"

LAYERDEPENDS_meta-dsandbox = "core"
LAYERSERIES_COMPAT_meta-dsandbox = "scarthgap"
